CREATE TABLE IF NOT EXISTS orders
(
    id                                    INT PRIMARY KEY,
    vendor_id                             INT,
    customer_id                           INT,
    status_id                             INT,
    payment_type_id                       INT,
    bank_id                               INT,
    delivery_area_id                      VARCHAR(255) CHARACTER SET utf8mb4,
    assignee_id                           INT,
    decline_reason_id                     INT,
    status_date                           TIMESTAMP,
    payment_status                        VARCHAR(255) CHARACTER SET utf8mb4,
    payment_attempts                      INT,
    customer_comment                      TEXT CHARACTER SET utf8mb4,
    customer_address_comment              TEXT CHARACTER SET utf8mb4,
    vendor_comment                        TEXT CHARACTER SET utf8mb4,
    order_comment                         TEXT CHARACTER SET utf8mb4,
    expedition_type                       VARCHAR(255) CHARACTER SET utf8mb4,
    delivery_address_line1                TEXT CHARACTER SET utf8mb4,
    delivery_address_phone1               BIGINT,
    delivery_address_city                 VARCHAR(255) CHARACTER SET utf8mb4,
    delivery_address_company              VARCHAR(255) CHARACTER SET utf8mb4,
    delivery_address_verified             INT,
    total_value                           INT,
    sub_total                             INT,
    calculated_total                      INT,
    service_fee                           INT,
    service_fee_total                     INT,
    delivery_fee                          INT,
    delivery_fee_forced                   INT,
    delivery_time                         INT,
    minimum_delivery_value                VARCHAR(255) CHARACTER SET utf8mb4,
    vat                                   INT,
    free_gift                             VARCHAR(255) CHARACTER SET utf8mb4,
    commission                            INT,
    commission_type                       VARCHAR(255) CHARACTER SET utf8mb4,
    tracking_identifier                   VARCHAR(255) CHARACTER SET utf8mb4,
    tracking_id                           INT,
    edited                                INT,
    source                                VARCHAR(255) CHARACTER SET utf8mb4,
    email_feedback                        INT,
    feedback_sent                         INT,
    pre_order                             INT,
    preOrder_deliveryTime                 TIMESTAMP,
    expected_delivery_time                TIMESTAMP,
    rider_pickup_date_time                TIMESTAMP,
    delivery_charge                       INT,
    service_charge                        INT,
    container_price                       INT,
    social_reason                         VARCHAR(255) CHARACTER SET utf8mb4,
    change_for                            VARCHAR(255) CHARACTER SET utf8mb4,
    archive                               INT,
    assignee_date                         TIMESTAMP,
    delivery_fee_original                 VARCHAR(255) CHARACTER SET utf8mb4,
    service_tax_total                     INT,
    platform                              VARCHAR(255) CHARACTER SET utf8mb4,
    vat_amount                            INT,
    created_at                            TIMESTAMP,
    updated_at                            TIMESTAMP,
    delivery_commission_enabled           INT,
    packaging_commission_enabled          INT,
    vat_included                          INT,
    products_vat_enabled                  INT,
    delivery_vat_enabled                  INT,
    packaging_vat_enabled                 INT,
    vat_enabled                           INT,
    vat_visible                           INT,
    app_version                           VARCHAR(255) CHARACTER SET utf8mb4,
    old_order_id                          VARCHAR(255) CHARACTER SET utf8mb4,
    deleted                               VARCHAR(255) CHARACTER SET utf8mb4,
    deleted_at                            TIMESTAMP,
    online_delivery_enabled               INT,
    user_address_id                       INT,
    replaced_by_order_id                  VARCHAR(255) CHARACTER SET utf8mb4,
    company_order_id                      VARCHAR(255) CHARACTER SET utf8mb4,
    device_id                             VARCHAR(255) CHARACTER SET utf8mb4,
    free_order                            INT,
    sepidz_order_id                       VARCHAR(255) CHARACTER SET utf8mb4,
    sepidz_status                         VARCHAR(255) CHARACTER SET utf8mb4,
    cash_back_amount                      INT,
    full_name                             VARCHAR(255) CHARACTER SET utf8mb4,
    vendor_title                          VARCHAR(255) CHARACTER SET utf8mb4,
    vendor_phone                          VARCHAR(255) CHARACTER SET utf8mb4,
    assignee_name                         VARCHAR(255) CHARACTER SET utf8mb4,
    payment_type_code                     VARCHAR(255) CHARACTER SET utf8mb4,
    bank_code                             VARCHAR(255) CHARACTER SET utf8mb4,
    status_code                           INT,
    notify_bodo_food                      INT,
    manual                                INT,
    has_delay                             INT,
    has_delay_disable                     VARCHAR(255) CHARACTER SET utf8mb4,
    delay_assignee_name                   VARCHAR(255) CHARACTER SET utf8mb4,
    decline_detail_id                     INT,
    sub_total_discount                    INT,
    vat_amount_discount                   INT,
    container_price_discount              INT,
    delivery_fee_discount                 INT,
    vendor_discount_share                 INT,
    vendor_pick_udid                      VARCHAR(255) CHARACTER SET utf8mb4,
    decline_comment                       TEXT CHARACTER SET utf8mb4,
    new_delivery_fee                      INT,
    is_commission_for_discount            INT,
    product_discount_value                INT,
    product_discount_vendor_share         INT,
    product_discount_type                 VARCHAR(255) CHARACTER SET utf8mb4,
    product_discount_is_for_all           INT,
    delta_value                           INT,
    product_discount_allowed_payment_type VARCHAR(255) CHARACTER SET utf8mb4,
    paid_by_credit                        INT,
    user_total_value                      INT,
    extra_sub_total                       INT,
    manually_completed_payment            VARCHAR(255) CHARACTER SET utf8mb4,
    sub_total_discount_zf_share           INT,
    container_price_discount_zf_share     INT,
    delivery_fee_discount_zf_share        INT,
    rider_pickup_time                     INT,
    in_place_delivery                     INT,
    real_submitted_at                     TIMESTAMP,
    need_for_call                         VARCHAR(255) CHARACTER SET utf8mb4,
    assigned_in_queue                     VARCHAR(255) CHARACTER SET utf8mb4,
    pre_order_user_request_time           TIMESTAMP,
    customer_delivered_at                 TIMESTAMP,
    order_coupon                          VARCHAR(255) CHARACTER SET utf8mb4,
    coupon_discount_amount                INT,
    coupon_discount_sf_share_amount       INT,
    special                               INT
);
