CREATE TABLE IF NOT EXISTS users
(
    id                              INT PRIMARY KEY,
    created_by                      INT,
    updated_by                      INT,
    username                        VARCHAR(255) CHARACTER SET utf8mb4,
    salt                            VARCHAR(255) CHARACTER SET utf8mb4,
    email                           VARCHAR(255) CHARACTER SET utf8mb4,
    password                        VARCHAR(255) CHARACTER SET utf8mb4,
    type                            VARCHAR(255) CHARACTER SET utf8mb4,
    status                          VARCHAR(255) CHARACTER SET utf8mb4,
    firstname                       VARCHAR(255) CHARACTER SET utf8mb4,
    lastname                        VARCHAR(255) CHARACTER SET utf8mb4,
    cellphone                       BIGINT,
    sex                             VARCHAR(255) CHARACTER SET utf8mb4,
    comment                         TEXT CHARACTER SET utf8mb4,
    credit                          INT,
    global                          INT,
    visible                         INT,
    birthday                        VARCHAR(255) CHARACTER SET utf8mb4,
    created_at                      TIMESTAMP,
    updated_at                      TIMESTAMP,
    locale                          VARCHAR(255) CHARACTER SET utf8mb4,
    user_membership_acquaintance_id INT,
    birth_date                      VARCHAR(255) CHARACTER SET utf8mb4,
    old_id                          INT,
    is_company                      INT,
    mobile_verification_token       VARCHAR(255) CHARACTER SET utf8mb4,
    is_mobile_verified              INT,
    membership_plan_expiry_date     VARCHAR(255) CHARACTER SET utf8mb4,
    membership_plan_id              INT,
    filename                        VARCHAR(255) CHARACTER SET utf8mb4,
    image_confirmed                 VARCHAR(255) CHARACTER SET utf8mb4,
    point                           INT,
    memberships                     VARCHAR(255) CHARACTER SET utf8mb4,
    secret_code                     VARCHAR(255) CHARACTER SET utf8mb4,
    picked_by                       INT,
    picked_at                       TIMESTAMP,
    sms_subscribed                  INT,
    email_subscribed                INT,
    card_number                     VARCHAR(255) CHARACTER SET utf8mb4
);
