CREATE TABLE IF NOT EXISTS device_adjustment_infos
(
    id                  INT PRIMARY KEY,
    app_id              VARCHAR(255),
    app_version         VARCHAR(255),
    app_name            VARCHAR(255),
    store               VARCHAR(255),
    tracker             VARCHAR(255),
    tracker_name        VARCHAR(255),
    is_organic          INT,
    click_referrer      VARCHAR(255),
    adjust_created_at   INT,
    installed_at        TIMESTAMP,
    created_at          TIMESTAMP,
    ad_id               VARCHAR(255),
    idfa                VARCHAR(255),
    android_id          VARCHAR(255),
    push_token          VARCHAR(255),
    conversion_duration VARCHAR(255),
    gps_adid            VARCHAR(255),
    match_type          VARCHAR(255),
    random_user_id      VARCHAR(255),
    last_tracker_name   VARCHAR(255),
    uninstalled_at      VARCHAR(255),
    country_subdivision VARCHAR(255),
    city                VARCHAR(255)
);
