CREATE TABLE IF NOT EXISTS payment_info
(
    id                  INT PRIMARY KEY,
    order_id            INT,
    created_by          INT,
    updated_by          INT,
    status              VARCHAR(255) CHARACTER SET utf8mb4,
    customer_name       VARCHAR(255) CHARACTER SET utf8mb4,
    receipt_date        VARCHAR(255) CHARACTER SET utf8mb4,
    order_date          VARCHAR(255) CHARACTER SET utf8mb4,
    total_amount        INT,
    bank_title          VARCHAR(255) CHARACTER SET utf8mb4,
    account_number      VARCHAR(255) CHARACTER SET utf8mb4,
    description         VARCHAR(255) CHARACTER SET utf8mb4,
    filename            VARCHAR(255) CHARACTER SET utf8mb4,
    created_at          TIMESTAMP,
    paid_at             TIMESTAMP,
    updated_at          TIMESTAMP,
    deleted             INT,
    bank_receipt_id     VARCHAR(255) CHARACTER SET utf8mb4,
    cellphone           BIGINT,
    card_number         VARCHAR(16) CHARACTER SET utf8mb4,
    user_id             INT,
    decrease_credit     VARCHAR(255) CHARACTER SET utf8mb4,
    reason              VARCHAR(255) CHARACTER SET utf8mb4,
    transfer_type       VARCHAR(255) CHARACTER SET utf8mb4,
    transfer_response   VARCHAR(255) CHARACTER SET utf8mb4,
    tracking_id         INT,
    card_owner          VARCHAR(255) CHARACTER SET utf8mb4,
    transfer_error_code INT,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE ON UPDATE CASCADE,

);
