CREATE TABLE IF NOT EXISTS vendor_accountings
(
    id                                  INT PRIMARY KEY,
    vendor_id                           INT,
    created_by                          VARCHAR(255) CHARACTER SET utf8mb4,
    updated_by                          VARCHAR(255) CHARACTER SET utf8mb4,
    title                               VARCHAR(255) CHARACTER SET utf8mb4,
    start_date                          TIMESTAMP,
    end_date                            TIMESTAMP,
    commission                          INT,
    total_sales                         DECIMAL(20, 2),
    online_sales                        DECIMAL(20, 2),
    cash_sales                          DECIMAL(20, 2),
    packaging_costs                     DECIMAL(20, 2),
    delivery_costs                      DECIMAL(20, 2),
    commission_value                    DECIMAL(20, 2),
    vat_value                           DECIMAL(20, 2),
    payable_value                       DECIMAL(20, 2),
    extra_costs                         DECIMAL(20, 2),
    created_at                          TIMESTAMP,
    updated_at                          TIMESTAMP,
    status                              VARCHAR(255) CHARACTER SET utf8mb4,
    sub_total                           DECIMAL(20, 2),
    order_count                         INT,
    payable_vat                         DECIMAL(20, 3),
    excel_file                          VARCHAR(255) CHARACTER SET utf8mb4,
    total_vat_value                     DECIMAL(20, 2),
    comment                             TEXT CHARACTER SET utf8mb4,
    vendor_accounting_period_id         VARCHAR(255) CHARACTER SET utf8mb4,
    serial_number                       INT,
    partial_extra_cost                  DECIMAL(20, 2),
    express_count                       INT,
    express_value                       DECIMAL(20, 2),
    express_commission                  DECIMAL(20, 2),
    express_commision_percent           INT,
    accounting_ignore                   INT,
    express_commision_amount            DECIMAL(20, 2),
    delivery_costs_cash                 DECIMAL(20, 2),
    packaging_costs_cash                DECIMAL(20, 2),
    delivery_costs_vat                  DECIMAL(20, 2),
    delta_value                         DECIMAL(20, 2),
    free_delivery_coupon_express        INT,
    discount                            DECIMAL(20, 2),
    snappbox_contract_commission_date   TIMESTAMP,
    partial_weekly_extra_cost           DECIMAL(20, 2),
    partial_daily_extra_cost            DECIMAL(20, 2),
    reference_code                      VARCHAR(255) CHARACTER SET utf8mb4,
    csv_imported_by                     INT,
    csv_imported_at                     TIMESTAMP,
    pay_express_commission              INT,
    delivery_costs_vendor_share         DECIMAL(20, 2),
    snapp_food_extra_payments           DECIMAL(20, 2),
    partial_daily_settlement_extra_cost DECIMAL(20, 2),
    cash_back                           DECIMAL(20, 2),
    voucher_and_discount                DECIMAL(20, 2),
    discounted_total_sale               DECIMAL(20, 2),
    discount_on_revenue                 DECIMAL(20, 2),
    total_service_fee                   DECIMAL(20, 2),
    express_income_adjustment           DECIMAL(20, 2),
    FOREIGN KEY (vendor_id) REFERENCES vendors (id) ON DELETE CASCADE ON UPDATE CASCADE
);
